### ISSUE TITLE
CORS - "Access-Control-Allow-Origin"

### ISSUE THREAD

**Issue by MrkacekVladimir** [SSSVT/ChatApp-Server_simpleJWT#3]
Unable to get **API response**.
Append **CORS** headers.

**EXAMPLE**:
https://stackoverflow.com/questions/6516591/how-to-implement-access-control-allow-origin-header-in-asp-net

**Comment by svejnohatomas** [comment]
Done

**Comment by svejnohatomas** [comment]
Done
